# Use an official Debian base image
FROM debian:trixie
LABEL org.opencontainers.image.source=https://github.com/qualcomm-linux/docker-pkg-build

# Prevent interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

COPY base-packages.txt /tmp/base-packages.txt

RUN apt-get update && \
    apt-get install -y $(cat /tmp/base-packages.txt | tr '\n' ' ') && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY extra-packages.txt /tmp/extra-packages.txt
COPY keyrings/ /tmp/keyrings/
COPY sources/trixie/qli.sources /tmp/qli.sources

RUN EXTRA_PACKAGES=$(tr -s '[:space:]' ',' < /tmp/extra-packages.txt) && \
    sbuild-createchroot --include="$EXTRA_PACKAGES" \
                        --arch=arm64 \
                        --components=main,contrib,non-free,non-free-firmware \
                        trixie \
                        /srv/chroot/trixie \
                        https://deb.debian.org/debian && \
    mkdir -p /srv/chroot/trixie/etc/apt/keyrings && \
    cp /tmp/keyrings/*.asc /srv/chroot/trixie/etc/apt/keyrings/ && \
    cp /tmp/qli.sources /srv/chroot/trixie/etc/apt/sources.list.d/
                        
# Set working directory
WORKDIR /workspace

# Default command
CMD [ "bash" ]
