name: Container Build And Upload
description: |
  Builds and uploads to GHCR (GitHub Container Registry) the container used to build the Qualcomm debian packages.
  Builds natively on an arm64 self-hosted runner. Images are uploaded on push to main, scheduled runs, and manual dispatches.

on:
  schedule:
    # Runs at 00:00 UTC every Monday
    - cron: '0 0 * * 1'

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/qcom-container-build-and-upload.yml'
      - '.github/actions/build_container/action.yml'
      - 'Dockerfiles/**'

  push:
    branches:
      - main
    paths:
      - '.github/workflows/qcom-container-build-and-upload.yml'
      - '.github/actions/build_container/action.yml'
      - 'Dockerfiles/**'

  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  QCOM_ORG_NAME: "qualcomm-linux"

  IMAGE_NAME: "pkg-builder"

jobs:

  # Build the arm64 natively using a self-hosted runner on an arm64 host
  # Cross compiling the image using buildx on an x86_64 host was tried but failed due to
  # issues with qemu and multiarch support in docker buildx.
  build-image-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Images
        uses: ./.github/actions/build_container
        with:
          arch: arm64

      - name: Upload Images
        uses: ./.github/actions/upload_containers
        # Only upload on trusted events that land code on main
        if: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        with:
          arch: arm64
          push-to-ghcr: "true"
          token: ${{ secrets.DEB_PKG_BOT_CI_TOKEN }}
          username: ${{ vars.DEB_PKG_BOT_CI_USERNAME }}
